name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: check if .hs files have changed
      run: git diff HEAD^ | grep ".hs"
    
    - uses: actions/setup-haskell@v1
      with:
        fetch-depth: 0
        ghc-version: '8.10.3'
        cabal-version: '3.2'
        
    - name: Test file execution
      run: | 
        set -e
        for f in *.hs; do runhaskell "${f}"; done
